function start(){
    // window.alert("Welcome to our Website")

    // let ans= window.confirm ("Are you ok?")
    
    // console.log(ans)

    // let show=window.prompt("Enter Number")
    // console.log(show);


        // let num1= parseInt(prompt("Enter Number")) // for addition parseint before addition
        // let num2=parseInt(prompt("Enter Number"))

        // window.alert(parseInt(show)+parseInt(shows))   // parseint after no. taken
        // window.alert(num1+num2)
        // let num1= (prompt("Enter Number")) 
        // let num2=(prompt("Enter Number"))

        // window.alert(num1-num2)
        // window.alert(num1*num2)
        // window.alert(num1/num2)
        // window.alert(num1%num2)


    // let ans= window.confirm ("Are you ok?")
    // if(ans==true){
    //     window.alert("yes I'm Ok")
    // }
    // else{
    //     window.alert("no I'm not Ok")
    // }
    // 07 dec 
    // let a= 9;
    // if(a%2==0){
    //     alert("Even")
    // }
    // else{
    //     alert("Odd")
    // }

//     let a=(prompt("Enter Number"))
//     // let a = 0;
//     if(a==0){
//         alert("Zero")
//     }
//     else if (a<0){
//         alert("negitive")
//     }
//     else{
//         alert("positive")
//     }
// let age = 18;


    // let age=prompt("Enter Age")
    // age<18 ? alert("Younger") : alert("Elder") 

// or
// let age=prompt("Enter Age")
// let ans = age >= 18 ? "Adult" : "Child" ;
// alert(ans)

// let num = 10;
// for (i= 1;i<=num ; i++)
//     console.log(i)

    let ans1= confirm ("Are you get Certificate")
    let ans2= confirm ("Are you completed your Course")
    if(ans1 && ans2){
    alert("you Get a Certificate")
    }
    else {
    alert("you don't Get a Certificate")
    }
}

start();