function start(){
    // window.alert("Welcome to our Website")

    // let ans= window.confirm ("Are you ok?")
    
    // console.log(ans)

    // let show=window.prompt("Enter Number")
    // console.log(show);


        // let num1= parseInt(prompt("Enter Number")) // for addition parseint before addition
        // let num2=parseInt(prompt("Enter Number"))

        // window.alert(parseInt(show)+parseInt(shows))   // parseint after no. taken
        // window.alert(num1+num2)
        // let num1= (prompt("Enter Number")) 
        // let num2=(prompt("Enter Number"))

        // window.alert(num1-num2)
        // window.alert(num1*num2)
        // window.alert(num1/num2)
        // window.alert(num1%num2)


    let ans= window.confirm ("Are you ok?")
    if(ans==true){
        window.alert("yes")
    }
    else{
        window.alert("no")
    }
}

start();